### ISSUE TITLE
Handling non-http errors

### ISSUE THREAD

**Issue by inacior** [inacior/is-my-env-alive#5]
`(node:92731) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'status' of undefined
    at _checkResponse (/Users/rinacio/.nvm/versions/node/v14.13.0/lib/node_modules/is-my-env-alive/lib/check.js:21:16)
    at module.exports (/Users/rinacio/.nvm/versions/node/v14.13.0/lib/node_modules/is-my-env-alive/lib/check.js:77:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:92731) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:92731) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by inacior** [comment]
Fixed in #7
